### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Hellowlol** [Hellowlol/bw_plex#3]
- [x] get better themes.
- [x] Make it easy to replace a bad theme
- [x] Analyze for previously on showname to detect recap.
- [x] credits
- [x] logging
- [x] error handling.
- [x] package.

Possible 
- [x] db export
- [ ] webserver api,, this should require a hashing metod. thus need to dl the entire file..

**Comment by swxxii** [comment]
Hey i just got this working and it is truly awesome. not sure if this is the right place to post so please advise. It would be great to bulk process and precompute the skip points on my entire library of unwatched shows. maybe there is already a way to do this?

**Comment by Hellowlol** [comment]
Yes it is. Use the process command
